package checktimetable;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;

public class WriteTimetable {
	
	public static void main(String[] args) {
		
		try {
			FileWriter writer = new FileWriter ("timetable1.html");
			writer.write("<!doctype html>\n");
			writer.write("<html>\n");
			writer.write("<head>\n");
			writer.write("    <title>Timetable</title>\n");
			writer.write("    <style type=\"text/css\">\n");
			writer.write("    body\n");
			writer.write("    {\n");
			writer.write("        font-family: arial;\n");
			writer.write("    }\n\n");
			writer.write("    th,td\n");
			writer.write("    {\n");
			writer.write("        margin: 0;\n");
			writer.write("        text-align: center;\n");
			writer.write("        border-collapse: collapse;\n");
			writer.write("        outline: 1px solid #e3e3e3;\n");
			writer.write("    }\n\n");
			writer.write("    td\n");
			writer.write("    {\n");
			writer.write("        padding: 5px 10px;\n");
			writer.write("    }\n\n");
			writer.write("    th\n");
			writer.write("    {\n");
			writer.write("        background: #666;\n");
			writer.write("        color: white;\n");
			writer.write("        padding: 5px 10px;\n");
			writer.write("    }\n\n");
			writer.write("    td:hover\n");
			writer.write("    {\n");
			writer.write("        cursor: pointer;\n");
			writer.write("        background: #666;\n");
			writer.write("        color: white;\n");
			writer.write("    }\n");
			writer.write("    </style>\n\n");
			writer.write("</head>\n");
			writer.write("<body>\n");
			writer.write("    <table width=\"80%\" align=\"center\" >\n");
			writer.write("    <div id=\"head_nav\">\n");
			writer.write("    <tr>\n");
			writer.write("        <th>Time</th>\n");
			writer.write("        <th>09:00 - 10:00</th>\n");
			writer.write("        <th>10:00 - 11:00</th>\n");
			writer.write("        <th>11:00 - 12:00</th>\n");
			writer.write("        <th>12:00 - 13:00</th>\n");
			writer.write("        <th>13:00 - 14:00</th>\n");
			writer.write("        <th>14:00 - 15:00</th>\n");
			writer.write("        <th>15:00 - 16:00</th>\n");
			writer.write("        <th>16:00 - 17:00</th>\n");
			writer.write("    </tr>\n");
			writer.write("    </div>\n\n");
			writer.write("    <tr>\n");
			writer.write("        <th>Monday</th>\n\n");
			writer.write("            <td>M1</td>\n");
			writer.write("            <td>M2</td>\n");
			writer.write("            <td>M3</td>\n");
			writer.write("            <td>M4</td>\n");
			writer.write("            <td>M5</td>\n");
			writer.write("            <td>M6</td>\n");
			writer.write("            <td>M7</td>\n");
			writer.write("            <td>M8</td>\n");
			writer.write("        </div>\n");
			writer.write("    </tr>\n\n");
			writer.write("    <tr>\n");
			writer.write("        <th>Tuesday</td>\n\n");
			writer.write("            <td>Tu1</td>\n");
			writer.write("            <td>Tu2</td>\n");
			writer.write("            <td>Tu3</td>\n");
			writer.write("            <td>Tu4</td>\n");
			writer.write("            <td>Tu5</td>\n");
			writer.write("            <td>Tu6</td>\n");
			writer.write("            <td>Tu7</td>\n");
			writer.write("            <td>Tu8</td>\n");
			writer.write("        </div>\n");
			writer.write("    </tr>\n\n");
			writer.write("    <tr>\n");
			writer.write("        <th>Wednesday</td>\n\n");
			writer.write("            <td>W1</td>\n");
			writer.write("            <td>W2</td>\n");
			writer.write("            <td>W3</td>\n");
			writer.write("            <td>W4</td>\n");
			writer.write("            <td>W5</td>\n");
			writer.write("            <td>W6</td>\n");
			writer.write("            <td>W7</td>\n");
			writer.write("            <td>W8</td>\n");
			writer.write("        </div>\n");
			writer.write("    </tr>\n\n");
			writer.write("    <tr>\n");
			writer.write("        <th>Thursday</td>\n\n");
			writer.write("            <td>Th1</td>\n");
			writer.write("            <td>Th2</td>\n");
			writer.write("            <td>Th3</td>\n");
			writer.write("            <td>Th4</td>\n");
			writer.write("            <td>Th5</td>\n");
			writer.write("            <td>Th6</td>\n");
			writer.write("            <td>Th7</td>\n");
			writer.write("            <td>Th8</td>\n");
			writer.write("        </div>\n");
			writer.write("    </tr>\n\n");
			writer.write("    <tr>\n");
			writer.write("        <th>Friday</td>\n\n");
			writer.write("            <td>F1</td>\n");
			writer.write("            <td>F2</td>\n");
			writer.write("            <td>F3</td>\n");
			writer.write("            <td>F4</td>\n");
			writer.write("            <td>F5</td>\n");
			writer.write("            <td>F6</td>\n");
			writer.write("            <td>F7</td>\n");
			writer.write("            <td>F8</td>\n");
			writer.write("        </div>\n");
			writer.write("    </tr>\n\n");
			writer.write("</body>\n");
			writer.write("</table>\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.write("\n");
			writer.close();
		} catch (IOException e) {
			e.printStackTrace();
		}

	}
}
